### ISSUE TITLE
PA2 Level 5 Evaluate on Construction

### ISSUE THREAD

**Issue by Fliprun** [nus-cs2030/2223-s2#875] opened 2023-04-15 17:00 UTC
# Summary
Even after changing my constructors to all use Supplier<T>, Evaluate still displays upon initializing a new DnC. Anyone have any idea what might have caused this?
I do not have any .get() calls in my constructors and of methods and immediately use Suppliers to wrap around the problems. Can't figure out why it still prints evaluate.

**Comment by edmundnwl** [comment] 2023-04-15 18:50
you also need to change the Function<T, Pair<T, T>> to Function<T, Pair<Supplier<T>, Supplier<T>>>

**Comment by jorwong** [comment] 2023-04-15 23:33
I am not sure what you have implemented. However, in my code i have also used OrElseGet to ensure the supplier is only calls get when it needs to

**Comment by Fliprun** [comment] 2023-04-16 00:51
> you also need to change the Function<T, Pair<T, T>> to Function<T, Pair<Supplier, Supplier>>

Yep did this as well, no difference sadly.

**Comment by Fliprun** [comment] 2023-04-16 02:00
> I am not sure what you have implemented. However, in my code i have also used OrElseGet to ensure the supplier is only calls get when it needs to

I'm hesitant to post my code since I'm unsure of how much I can send but I only have .get() methods in left(), right() and solve(bop). I'll give this a shot and hopefully something changes.

**Comment by edmundnwl** [comment] 2023-04-16 02:07
I think the very first evaluated is unavoidable when you initialise the DnC as instructed by them. Its the subsequent DnCs that are made in the evaluation of solve(bop) that shouldn't have that evaluation because it uses an of method that takes in a supplier instead this time.

**Comment by granolaluvr69** [comment] 2023-04-16 02:35
> I think the very first evaluated is unavoidable when you initialise the DnC as instructed by them where the first argument is the PairOf(). Its the subsequent DnCs that are made in the evaluation of solve(bop) that shouldn't have that evaluation because it uses an of method that takes in a supplier instead this time.
<img width="779" alt="Screenshot 2023-04-16 at 10 33 07 AM" src="https://user-images.githubusercontent.com/120318851/232263025-7757af5d-4309-465d-b796-25b17464eb76.png">
Hi Edmund, I think that the test cases suggest that we avoid the evaluation of the DnC upon creation of the object. 
If anyone knows how to avoid doing so, any tips would be appreciated.
Thanks!

**Comment by edmundnwl** [comment] 2023-04-16 02:42
> Hi Edmund, I think that the test cases suggest that we avoid the evaluation of the DnC upon creation of the object. If anyone knows how to avoid doing so, any tips would be appreciated. Thanks!

Are you able to check if the first argument was this test case was pairOf(5, 7) or () -> pairOf(5, 7)? because if its the first case I really think that evaluation is unavoidable. My of method simply takes the input of T and assigns it as () -> T. It is another of method that takes in a supplier<T> that is assigned to supplier<T> directly that no evaluation will take place

**Comment by SimonSeeYongsheng** [comment] 2023-04-16 03:02
> > I think the very first evaluated is unavoidable when you initialise the DnC as instructed by them where the first argument is the PairOf(). Its the subsequent DnCs that are made in the evaluation of solve(bop) that shouldn't have that evaluation because it uses an of method that takes in a supplier instead this time.
> 
> <img alt="Screenshot 2023-04-16 at 10 33 07 AM" width="779" src="https://user-images.githubusercontent.com/120318851/232263025-7757af5d-4309-465d-b796-25b17464eb76.png">
> 
> Hi Edmund, I think that the test cases suggest that we avoid the evaluation of the DnC upon creation of the object. If anyone knows how to avoid doing so, any tips would be appreciated. Thanks!

Hi, I have the same issue as you, I think the issue is the that our variable type for property T is T and not Supplier<T>, this would cause it to eagerly evaluate.

**Comment by Fliprun** [comment] 2023-04-16 04:03
> > Hi Edmund, I think that the test cases suggest that we avoid the evaluation of the DnC upon creation of the object. If anyone knows how to avoid doing so, any tips would be appreciated. Thanks!
> 
> Are you able to check if the first argument was this test case was pairOf(5, 7) or () -> pairOf(5, 7)? because if its the first case I really think that evaluation is unavoidable. My of method simply takes the input of T and assigns it as () -> T. It is another of method that takes in a supplier that is assigned to supplier directly that no evaluation will take place
> 
> Besides that, I only have .get() in my left(), right() and solve(bop), once each.


Well looking at the test case given,
![image](https://user-images.githubusercontent.com/128240191/232265734-00ac5ea9-a697-45a7-bcb2-b0e00efdce72.png)
It shows that the first argument is indeed a supplier and evaluate is not printed. 


> > > I think the very first evaluated is unavoidable when you initialise the DnC as instructed by them where the first argument is the PairOf(). Its the subsequent DnCs that are made in the evaluation of solve(bop) that shouldn't have that evaluation because it uses an of method that takes in a supplier instead this time.
> > 
> > 
> > <img alt="Screenshot 2023-04-16 at 10 33 07 AM" width="779" src="https://user-images.githubusercontent.com/120318851/232263025-7757af5d-4309-465d-b796-25b17464eb76.png">
> > Hi Edmund, I think that the test cases suggest that we avoid the evaluation of the DnC upon creation of the object. If anyone knows how to avoid doing so, any tips would be appreciated. Thanks!
> 
> Hi, I have the same issue as you, I think the issue is the that our variable type for property T is T and not Supplier of T, this would cause it to eagerly evaluate.

My variable type for the first property is Supplier<T> and it unfortunately still prints evaluate.

**Comment by Aron113** [comment] 2023-04-16 06:11
might be helpful to recompile all the files and open up jshell again just in case its using the older DnC version

**Comment by Huanqing-Mao** [comment] 2023-04-16 07:53
Can I ask whether our final solution will be tested against cases in level1 ~ 3? cos level 5 asked us to use pair<Supplier, supplier>, but before level4 we were using pair<T, T> only...or are we supposed to create a new property to fit level 5

**Comment by SimonSeeYongsheng** [comment] 2023-04-16 07:57
Okay I found a way to solve it, you just have to create a new DnC in solve(binary) and use that new DnC object in the return

**Comment by SimonSeeYongsheng** [comment] 2023-04-16 08:01
> Can I ask whether our final solution will be tested against cases in level1 ~ 3? cos level 5 asked us to use pair<Supplier, supplier>, but before level4 we were using pair<T, T> only...or are we supposed to create a new property to fit level 5

You should have a Optional<T> and a Supplier<T> but you should only have one recursive function wrapped in an Optional

**Comment by edmundnwl** [comment] 2023-04-16 08:04
> Can I ask whether our final solution will be tested against cases in level1 ~ 3? cos level 5 asked us to use pair<Supplier, supplier>, but before level4 we were using pair<T, T> only...or are we supposed to create a new property to fit level 5

what I did was convert the Function<T, Pair<T, T>> given as an argument to a Function<T, Pair<Supplier<T>, Supplier<T>>> within the of method itself

**Comment by Huanqing-Mao** [comment] 2023-04-16 08:57
> > Can I ask whether our final solution will be tested against cases in level1 ~ 3? cos level 5 asked us to use pair<Supplier, supplier>, but before level4 we were using pair<T, T> only...or are we supposed to create a new property to fit level 5
> 
> what I did was convert the Function<T, Pair<T, T>> given as an argument to a Function<T, Pair<Supplier, Supplier>> within the of method itself

Hi can I ask how did you do that?

**Comment by SimonSeeYongsheng** [comment] 2023-04-16 12:01
> > > Can I ask whether our final solution will be tested against cases in level1 ~ 3? cos level 5 asked us to use pair<Supplier, supplier>, but before level4 we were using pair<T, T> only...or are we supposed to create a new property to fit level 5
> > 
> > 
> > what I did was convert the Function<T, Pair<T, T>> given as an argument to a Function<T, Pair<Supplier, Supplier>> within the of method itself
> 
> Hi can I ask how did you do that?

try using andThen()

**Closed** 2023-04-18 01:59 UTC
Labels: :notebook: PA 2
